name: CI
on: [push]

jobs:
    windows-latest-debug:
        runs-on: windows-latest

        steps:
            - name: Clone
              uses: actions/checkout@v1

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Configure
              run: cmake -S . -B .\build
              
            - name: View build
              run: dir .\build
              
            - name: Compile main
              run: msbuild whisper.cpp.sln

            - name: View build
              run: dir .\build
              
            - name: View whole
              run: dir .
