name: CI
on: [push]

jobs:
    windows-latest:
        runs-on: windows-latest

        steps:
            - name: Clone
              uses: actions/checkout@v1

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Configure
              run: cmake -S . -B .\build
              
            - name: Compile main
              run: msbuild build\whisper.cpp.sln

            - name: View build
              run: dir .\build
              
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v3.1.1
              with:
                # Artifact name
                name: Build
                path: build\bin
